;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<AppWindow>>>;;;
[AppWindow]
DpiWindowSizeFactor=1
WindowPosition=0,67
WindowSize=1800,1012
;;;<<<ImGui_655921752_Default>>>;;;
[Window][###Statistics]
Collapsed=0
DockId=0x0000000C

[Window][###UndoHistory]
Collapsed=0
DockId=0x0000000E

[Window][###VIDEOPLAYER]
Pos=0,21
Size=1474,741
Collapsed=0
DockId=0x00000005,0

[Window][###Timeline]
Pos=271,913
Size=1529,99
Collapsed=0
DockId=0x00000008,0

[Window][###Controls]
Pos=0,913
Size=269,99
Collapsed=0
DockId=0x00000007,0

[Window][###ScriptTimeline]
Pos=0,764
Size=1800,147
Collapsed=0
DockId=0x00000004,0

[Window][###ScriptingMode]
Pos=1476,21
Size=324,282
Collapsed=0
DockId=0x0000000D,0

[Window][###ActionEditor]
Pos=1476,481
Size=324,281
Collapsed=0
DockId=0x0000000A,0

[Window][###TrackInfo]
Pos=1476,305
Size=324,174
Collapsed=0
DockId=0x0000000C,0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][###Preferences]
Pos=60,60
Size=460,400
Collapsed=0

[Window][###Routing]
Pos=60,60
Size=700,450
Collapsed=0

[Docking][Data]
DockSpace             ID=0xAFC85805 Window=0x079D3A04 Pos=0,21 Size=1800,991 Split=Y
  DockNode            ID=0x00000001 Parent=0xAFC85805 SizeRef=1800,890 Split=Y
    DockNode          ID=0x00000003 Parent=0x00000001 SizeRef=1800,741 Split=X
      DockNode        ID=0x00000005 Parent=0x00000003 SizeRef=1474,741 CentralNode=1 Selected=0x92A3E579
      DockNode        ID=0x00000006 Parent=0x00000003 SizeRef=324,741 Split=Y
        DockNode      ID=0x00000009 Parent=0x00000006 SizeRef=324,458 Split=Y
          DockNode    ID=0x0000000B Parent=0x00000009 SizeRef=324,282 Split=Y
            DockNode  ID=0x0000000D Parent=0x0000000B SizeRef=324,140 Selected=0x101DFBE6
            DockNode  ID=0x0000000E Parent=0x0000000B SizeRef=324,140
          DockNode    ID=0x0000000C Parent=0x00000009 SizeRef=324,174 Selected=0x05FC9F03
        DockNode      ID=0x0000000A Parent=0x00000006 SizeRef=324,281 Selected=0xBFD95273
    DockNode          ID=0x00000004 Parent=0x00000001 SizeRef=1800,147 Selected=0x53B65E23
  DockNode            ID=0x00000002 Parent=0xAFC85805 SizeRef=1800,99 Split=X
    DockNode          ID=0x00000007 Parent=0x00000002 SizeRef=269,99 Selected=0xB6318CDC
    DockNode          ID=0x00000008 Parent=0x00000002 SizeRef=1529,99 Selected=0x597925B7

;;;<<<Layout_655921752_Default>>>;;;
[Visibility]
1027224670_Video___VIDEOPLAYER=true
2099001059_Controls___Controls=true
2669570274_Scripting___ScriptingMode=true
2788833077_Undo_History___UndoHistory=false
3106060196_Statistics___Statistics=false
3269374545_Action_Editor___ActionEditor=true
3632909399_Track_Info___TrackInfo=true
386783549_Timeline___ScriptTimeline=true
3996403040_Progress___Timeline=true
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=false
ShowFps=true
[Theme]
Name=DarculaDarker
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{"ActionDock":10,"BottomDock":8,"ControlsDock":7,"MainDockSpace":2949142533,"RightDock":13,"StatsDock":12,"TimelineDock":4,"UndoDock":14}}
